"""empty message

Revision ID: 509eaf4a38a3
Revises: 4e1d5bea728a
Create Date: 2019-09-09 13:38:36.411333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '509eaf4a38a3'
down_revision = '4e1d5bea728a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###
